- name: Deploy Bookstore Web App to EC2 Instance
  hosts: app-server

  tasks: 
    - name: create app directory
      file:
        path: /home/ec2-user/bookstore-app/
        state: directory
        mode: '0755'

    - name: Download artifact from Nexus repo
      maven_artifact:
        group_id: com.bookstore
        artifact_id: bookstore
        version: 0.0.1-SNAPSHOT
        extension: jar
        repository_url: 'http://ec2-52-91-212-69.compute-1.amazonaws.com:8081/repository/maven-releases/'
        username: admin
        password: admin123
        dest: /home/ec2-user/bookstore-app/bookstore-0.0.1-SNAPSHOT.jar

    - name: Deploy jar file to app server
      shell: java -jar bookstore-0.0.1-SNAPSHOT.jar
      args: 
        chdir: /home/ec2-user/bookstore-app/


