pipeline {
    agent any
    stages {
        stage('Build app') { 
            steps {
                sh """
                cd Bookstore && \
                mvn clean install -DskipTest
                """
            }        
        }
    }
         post {
        // Clean after build
        always {
            cleanWs()
        }
    }
}


