pipeline {
    agent {
        docker { image 'maven:3.8.6-openjdk-8' }
    }
    stages {
        stage('Build app') {
            dir('Bookstore') {
                steps {
                    sh """
                    mvn clean package -DskipTests
                    """
                }        
            } 
        }
    }
         post {
        // Clean after build
        always {
            cleanWs()
        }
    }
}


