pipeline {
    agent {
        docker { image 'maven:3.8.6-openjdk-8' }
    }
    stages {
        stage('Build app') { 
            steps {
                sh """
                cd bookstore-web-app && \
                mvn clean install -DskipTest
                """
            }        
        }
    }
         post {
        // Clean after build
        always {
            cleanWs()
        }
    }
}


